# Generated by Django 4.2.1 on 2023-05-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pet_freindly',
            new_name='pet_friendly',
        ),
    ]
