# Generated by Django 4.1.4 on 2023-01-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("experiences", "0002_experiences_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perks",
            options={"verbose_name_plural": "Perks"},
        ),
        migrations.AddField(
            model_name="experiences",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
